# Build workflow for GitHub Actions
# Run build script on tag push on master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - name: run build script
        # run build.sh in .github/build.sh
        run: bash -c "cd .github && ./build.sh"
      - name: Create tag
        # create tag from version string in manifest.json
        run: bash -c "cd github && git tag -a v$(jq -r '.version' manifest.json) -m 'Release v$(jq -r '.version' manifest.json)' && git push origin v$(jq -r '.version' manifest.json) && git push --tags"
      # push to github dist/netmonitor-<version>.zip
      - name: Push release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: true
          title: "Development Build"
          files: |
            dist/netmonitor-v$(jq -r '.version' manifest.json).zip
