# Build workflow for GitHub Actions
# Run build script on tag push on master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - name: run build script
      # save version name from manifest.json to github variable
        # run build.sh in .github/build.sh
        run: sh .github/build.sh
        shell: bash
      # push to github dist/netmonitor-<version>.zip
      - name: Push release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: true
          title: "Netmonitor Latest"
          files: |
            dist/netmonitor-v*.zip
